name: Despliegue automático a producción

on:
  push:
    branches:
      - main

jobs:
  pruebas_y_despliegue:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 📦 Instalar dependencias
        run: npm install

      - name: ✅ Ejecutar pruebas con Jest
        run: npm test

      - name: 🚀 Desplegar en servidor vía SSH
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/gestion-ventas
            sudo git pull origin main
            sudo docker-compose down
            sudo docker-compose up -d --build
